---
- hosts: all
  become: true

  handlers:
    - name: Restart cron
      ansible.builtin.systemd:
        name: cron
        state: restarted


  pre_tasks:
    - name: apt
      apt:
        update_cache: true
        upgrade: 'yes'
        cache_valid_time: 600

  tasks:

    - import_tasks: tasks/auto-updates.yml

    # Timezone
    - name: Set Timezone.
      timezone:
        name: Europe/Paris
      register: timezone

    - name: install NTP.
      apt:
        name: ntp
        state: present
      notify:
        - Restart cron

    # Firewall config
    - name: disable firewall.
      community.general.ufw:
        state: disabled
    - name: allow outgoing.
      community.general.ufw:
        default: allow
        direction: outgoing
    - name: deny incoming
      community.general.ufw:
        default: deny
        direction: incoming
        log: true
    - name: Allow incoming from home network.
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
      with_items:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
    - name: allow k3s Api.
      community.general.ufw:
        rule: allow
        port: '6443'
        proto: tcp
    - name: enable firewall
      community.general.ufw:
        state: enabled

    # install fail2ban

    - name: install fail2ban
      apt:
        name:
          - fail2ban
        state: present
        update_cache: true
    - name: copy conf
      ansible.builtin.copy:
        src: files/fail2ban.local
        dest: /etc/fail2ban/fail2ban.local
        owner: root
        group: root
    - name: copy jail
      ansible.builtin.copy:
        src: files/jail.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
    - name: bounce fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        state: restarted
