---
- name: auto-update enable
  apt:
    name: 
      - unattended-upgrades
    state: present
    update_cache: true
    
- name: copy config file
  ansible.builtin.copy:
    src: files/{{ item.src }}
    dest: /etc/apt/apt.conf.d/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 50unattended-upgrades, dest: 50unattended-upgrades }
    - { src: 20auto-upgrades, dest: 20auto-upgrades }